version: 0.2

phases:
    build:
        commands:
          - echo Build started on `date`
          - |
            echo "------------------build app image-----------------------------------------------"
            set -e
            cd $CODEBUILD_SRC_DIR
            docker build .
