version: 0.2

phases:
    pre_build:
        commands:
          - echo Logging in to Amazon ECR...
          - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
          - ACCOUNT_ID=$(aws sts get-caller-identity|jq -r '.Account')
          - IMAGE_TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION
          - |
            echo "-------------------pre_build app------------------------------------------------"
            APP_IMAGE=DEMO_IMAGE
            APP_REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$APP_IMAGE
            aws ecr create-repository \
              --repository-name $APP_IMAGE \
              --image-scanning-configuration scanOnPush=true \
              --region $AWS_DEFAULT_REGION || true
            echo "--------------------------------------------------------------------------------"
    build:
        commands:
          - echo Build started on `date`
          - |
            echo "------------------build app image-----------------------------------------------"
            set -e
            cd $CODEBUILD_SRC_DIR
            echo Building $APP_IMAGE:$IMAGE_TAG...
            docker build . -t $APP_IMAGE:$IMAGE_TAG
            echo Tagging $APP_REPOSITORY_URI:$IMAGE_TAG...
            docker tag $APP_IMAGE:$IMAGE_TAG $APP_REPOSITORY_URI:$IMAGE_TAG
            echo "--------------------------------------------------------------------------------"

    post_build:
        commands:
          - echo Build completed on `date`
          - |
            echo "------------------push app image------------------------------------------------"
            docker push $APP_REPOSITORY_URI:$IMAGE_TAG
            echo "--------------------------------------------------------------------------------"

